name: Docker Compose Deployment (SSH)
author: 'humbertocrispim'
branding:
  icon: server
  color: purple
description: SSH into host and deploy repository with Docker-Compose
inputs:
  ssh_private_key:
    description: Private SSH key used for logging into remote system.
    required: true
  ssh_host:
    description: Remote host name.
    required: true
  ssh_port:
    description: Remote SSH port.
    default: '22'
    required: true
  ssh_user:
    description: Remote user name.
    required: true
  docker_compose_prefix:
    description: Prefix for docker-compose containers.
    required: true
  docker_compose_filename:
    description: Docker compose file to use
    default: docker-compose.yml
  docker_down:
    description: Optional Used to specify flags to pass to the docker-compose down command during cleanup ("true" or "false"). 
    default: 'false'
  pull:
    description: Docker Compose pull images.
    default: 'false'   
  use_stack:
    description: Use docker stack instead of docker compose ("true" or "false").
    default: 'false'
  docker_env:
    description: Docker Environment variables.
  docker_env_file:
    description: Docker Environment variables.
  after_deploy:
    description: Commands to run after deployment.
    default: 'echo "After deploy"'
  before_deploy:
    description: Commands to run before deployment.
    default: 'echo "Before deploy"'
runs:
  using: docker
  image: Dockerfile
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    DOCKER_COMPOSE_FILENAME: ${{ inputs.docker_compose_filename }}
    DOCKER_COMPOSE_PREFIX: ${{ inputs.docker_compose_prefix }}
    USE_DOCKER_STACK: ${{ inputs.use_stack }}
    DOCKER_ENV: ${{ inputs.docker_env }}
    DOCKER_ENV_FILE: ${{ inputs.docker_env_file }}
    PULL: ${{ inputs.pull }}
    DOCKER_DOWN: ${{ inputs.docker_down }}
    BEFORE_DEPLOY: ${{ inputs.before_deploy }}
    AFTER_DEPLOY: ${{ inputs.after_deploy }}